import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  const { prompt, scenario } = await req.json();

  let content = '';
  if (scenario === 'email') {
    content = `
      <h2>Markdown Profit Optimization Campaign</h2>
      <table border="1" cellpadding="8" style="border-collapse:collapse;">
        <thead>
          <tr>
            <th>Name</th><th>SKU</th><th>Category</th><th>Current Price</th><th>New Price</th>
            <th>Discount %</th><th>Stock</th><th>Days Left</th><th>Holding Cost/Day</th><th>Est. Uplift</th>
          </tr>
        </thead>
        <tbody>
          ${prompt.split('\n').filter(line => line.includes('SKU:')).map(line => {
            const matches = line.match(/(.+?) \(SKU: (.+?), Category: (.+?)\): Current \$([\d.]+), Markdown (\d+)% → New \$([\d.]+), Stock: (\d+), Days Left: (\d+), Holding Cost\/Day: \$([\d.]+), Est. Uplift: \$([\d.]+)/);
            if (!matches) return '';
            const [, name, sku, category, currentPrice, discountPct, newPrice, stock, daysLeft, holdingCost, uplift] = matches;
            return `<tr>
              <td>${name}</td><td>${sku}</td><td>${category}</td><td>$${currentPrice}</td><td>$${newPrice}</td>
              <td>${discountPct}%</td><td>${stock}</td><td>${daysLeft}</td><td>$${holdingCost}</td><td>$${uplift}</td>
            </tr>`;
          }).join('')}
        </tbody>
      </table>
      <p style="color:green;">Estimated total profit uplift: <b>$XXX.XX</b></p>
      <small>Generated by pricepilot.ai using competitor pricing, elasticity, and holding cost data.</small>
    `;
  } else {
    content = `
      <div style="font-family:sans-serif;padding:12px;background:#fffbe7;">
        <h3>🔥 Clearance Alert!</h3>
        <ul>
        ${prompt.split('\n').filter(line => line.includes('% off')).map(line => `<li>${line}</li>`).join('')}
        </ul>
        <p>Shop now before clearance ends! <b>#Clearance #Deals #LastChance</b></p>
        <small>Generated by pricepilot.ai</small>
      </div>
    `;
  }

  return NextResponse.json({ content });
}
