import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import Navbar from '@/app/components/Navbar';

import './globals.css';
import { ClearanceProvider } from '@/app/contexts/ClearanceContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Price Pilot AI',
  description: 'Generated by create next app',
  icons: {
    icon: './pricepilot-logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClearanceProvider>
          <Navbar />
          {children}
        </ClearanceProvider>
      </body>
    </html>
  );
}
