import { PrismaClient } from '@/app/generated/prisma';
import { D } from './utils.js';

interface Channel {
  id: bigint;
  name: string;
}

export async function seedSales(
  prisma: PrismaClient,
  productBySku: Record<string, bigint>,
  channels: Channel[],
) {
  console.log('  💰 Seeding sales data...');

  await prisma.salesDaily.createMany({
    data: [
      // Product 1 (WIN-JKT-001) - Economic progression: Higher price = Lower demand
      // Period 1: Higher price ($90), lower demand (4-7 units)
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: channels[0].id,
        saleDate: new Date('2024-09-01'),
        unitsSold: 5,
        avgUnitPrice: D('91.00'),
        promoFlag: false,
        returnRate: D('2.10'),
        grossMargin: D('117.00'),
      },
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: null,
        saleDate: new Date('2024-09-02'),
        unitsSold: 4,
        avgUnitPrice: D('89.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('92.00'),
      },
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: channels[1].id,
        saleDate: new Date('2024-09-03'),
        unitsSold: 6,
        avgUnitPrice: D('90.00'),
        promoFlag: false,
        returnRate: D('1.50'),
        grossMargin: D('144.00'),
      },
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: channels[0].id,
        saleDate: new Date('2024-09-04'),
        unitsSold: 5,
        avgUnitPrice: D('92.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('122.50'),
      },
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: null,
        saleDate: new Date('2024-09-05'),
        unitsSold: 7,
        avgUnitPrice: D('88.00'),
        promoFlag: true,
        returnRate: D('3.20'),
        grossMargin: D('154.00'),
      },

      // Period 2: Medium price ($81), medium demand (8-12 units)
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-01'),
        unitsSold: 9,
        avgUnitPrice: D('82.00'),
        promoFlag: false,
        returnRate: D('1.60'),
        grossMargin: D('207.00'),
      },
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-02'),
        unitsSold: 11,
        avgUnitPrice: D('80.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('242.00'),
      },
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: null,
        saleDate: new Date('2024-10-03'),
        unitsSold: 10,
        avgUnitPrice: D('81.00'),
        promoFlag: false,
        returnRate: D('2.40'),
        grossMargin: D('220.00'),
      },
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-04'),
        unitsSold: 8,
        avgUnitPrice: D('83.00'),
        promoFlag: true,
        returnRate: null,
        grossMargin: D('184.00'),
      },
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-05'),
        unitsSold: 12,
        avgUnitPrice: D('79.00'),
        promoFlag: false,
        returnRate: D('3.10'),
        grossMargin: D('252.00'),
      },

      // Period 3: Lower price ($72), higher demand (14-18 units)
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-18'),
        unitsSold: 16,
        avgUnitPrice: D('73.00'),
        promoFlag: false,
        returnRate: D('1.40'),
        grossMargin: D('336.00'),
      },
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: null,
        saleDate: new Date('2024-10-19'),
        unitsSold: 14,
        avgUnitPrice: D('71.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('266.00'),
      },
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-20'),
        unitsSold: 18,
        avgUnitPrice: D('72.00'),
        promoFlag: false,
        returnRate: D('2.20'),
        grossMargin: D('378.00'),
      },
      {
        productId: productBySku['WIN-JKT-001'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-21'),
        unitsSold: 15,
        avgUnitPrice: D('74.00'),
        promoFlag: true,
        returnRate: null,
        grossMargin: D('315.00'),
      },

      // Product 2 (SUM-TOP-002) - Economic progression: $35 -> $31.50 -> $28
      // Period 1: Higher price ($35), lower demand (6-9 units)
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: channels[0].id,
        saleDate: new Date('2024-09-01'),
        unitsSold: 7,
        avgUnitPrice: D('36.00'),
        promoFlag: false,
        returnRate: D('1.80'),
        grossMargin: D('119.00'),
      },
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: null,
        saleDate: new Date('2024-09-02'),
        unitsSold: 6,
        avgUnitPrice: D('34.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('96.00'),
      },
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: channels[1].id,
        saleDate: new Date('2024-09-03'),
        unitsSold: 8,
        avgUnitPrice: D('35.00'),
        promoFlag: false,
        returnRate: D('2.10'),
        grossMargin: D('136.00'),
      },
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: channels[0].id,
        saleDate: new Date('2024-09-04'),
        unitsSold: 7,
        avgUnitPrice: D('37.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('126.00'),
      },
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: null,
        saleDate: new Date('2024-09-05'),
        unitsSold: 9,
        avgUnitPrice: D('33.00'),
        promoFlag: true,
        returnRate: D('1.50'),
        grossMargin: D('144.00'),
      },

      // Period 2: Medium price ($31.50), medium demand (10-14 units)
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-01'),
        unitsSold: 12,
        avgUnitPrice: D('32.00'),
        promoFlag: false,
        returnRate: D('1.90'),
        grossMargin: D('216.00'),
      },
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-02'),
        unitsSold: 11,
        avgUnitPrice: D('31.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('187.00'),
      },
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: null,
        saleDate: new Date('2024-10-03'),
        unitsSold: 13,
        avgUnitPrice: D('31.50'),
        promoFlag: false,
        returnRate: D('2.10'),
        grossMargin: D('214.50'),
      },
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-04'),
        unitsSold: 10,
        avgUnitPrice: D('33.00'),
        promoFlag: true,
        returnRate: null,
        grossMargin: D('180.00'),
      },
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-05'),
        unitsSold: 14,
        avgUnitPrice: D('30.00'),
        promoFlag: false,
        returnRate: D('1.60'),
        grossMargin: D('224.00'),
      },

      // Period 3: Lower price ($28), higher demand (16-20 units)
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-18'),
        unitsSold: 18,
        avgUnitPrice: D('28.50'),
        promoFlag: false,
        returnRate: D('1.30'),
        grossMargin: D('297.00'),
      },
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: null,
        saleDate: new Date('2024-10-19'),
        unitsSold: 16,
        avgUnitPrice: D('27.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('240.00'),
      },
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-20'),
        unitsSold: 20,
        avgUnitPrice: D('28.00'),
        promoFlag: false,
        returnRate: D('2.00'),
        grossMargin: D('340.00'),
      },
      {
        productId: productBySku['SUM-TOP-002'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-21'),
        unitsSold: 17,
        avgUnitPrice: D('29.00'),
        promoFlag: true,
        returnRate: null,
        grossMargin: D('289.00'),
      },

      // Product 3 (RUN-SHOE-003) - Economic progression: $100 -> $90 -> $80
      // Period 1: Higher price ($100), lower demand (2-5 units)
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: channels[0].id,
        saleDate: new Date('2024-09-01'),
        unitsSold: 3,
        avgUnitPrice: D('102.00'),
        promoFlag: false,
        returnRate: D('3.50'),
        grossMargin: D('96.00'),
      },
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: null,
        saleDate: new Date('2024-09-02'),
        unitsSold: 2,
        avgUnitPrice: D('98.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('56.00'),
      },
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: channels[1].id,
        saleDate: new Date('2024-09-03'),
        unitsSold: 4,
        avgUnitPrice: D('100.00'),
        promoFlag: false,
        returnRate: D('2.10'),
        grossMargin: D('136.00'),
      },
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: channels[0].id,
        saleDate: new Date('2024-09-04'),
        unitsSold: 3,
        avgUnitPrice: D('104.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('102.00'),
      },
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: null,
        saleDate: new Date('2024-09-05'),
        unitsSold: 5,
        avgUnitPrice: D('96.00'),
        promoFlag: true,
        returnRate: D('1.80'),
        grossMargin: D('160.00'),
      },

      // Period 2: Medium price ($90), medium demand (6-9 units)
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-01'),
        unitsSold: 7,
        avgUnitPrice: D('91.00'),
        promoFlag: false,
        returnRate: D('2.20'),
        grossMargin: D('203.00'),
      },
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-02'),
        unitsSold: 6,
        avgUnitPrice: D('89.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('162.00'),
      },
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: null,
        saleDate: new Date('2024-10-03'),
        unitsSold: 8,
        avgUnitPrice: D('90.00'),
        promoFlag: false,
        returnRate: D('1.90'),
        grossMargin: D('216.00'),
      },
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-04'),
        unitsSold: 7,
        avgUnitPrice: D('92.00'),
        promoFlag: true,
        returnRate: null,
        grossMargin: D('189.00'),
      },
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-05'),
        unitsSold: 9,
        avgUnitPrice: D('88.00'),
        promoFlag: false,
        returnRate: D('2.40'),
        grossMargin: D('234.00'),
      },

      // Period 3: Lower price ($80), higher demand (10-14 units)
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-18'),
        unitsSold: 12,
        avgUnitPrice: D('81.00'),
        promoFlag: false,
        returnRate: D('1.50'),
        grossMargin: D('276.00'),
      },
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: null,
        saleDate: new Date('2024-10-19'),
        unitsSold: 10,
        avgUnitPrice: D('79.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('210.00'),
      },
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-20'),
        unitsSold: 14,
        avgUnitPrice: D('80.00'),
        promoFlag: false,
        returnRate: D('2.30'),
        grossMargin: D('322.00'),
      },
      {
        productId: productBySku['RUN-SHOE-003'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-21'),
        unitsSold: 11,
        avgUnitPrice: D('82.00'),
        promoFlag: true,
        returnRate: null,
        grossMargin: D('253.00'),
      },

      // Product 4 (BEAN-HAT-004) - Economic progression: $12 -> $10.80 -> $9.60
      // Period 1: Higher price ($12), lower demand (8-12 units)
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: channels[0].id,
        saleDate: new Date('2024-09-01'),
        unitsSold: 9,
        avgUnitPrice: D('12.50'),
        promoFlag: false,
        returnRate: D('1.20'),
        grossMargin: D('90.00'),
      },
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: null,
        saleDate: new Date('2024-09-02'),
        unitsSold: 8,
        avgUnitPrice: D('11.50'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('72.00'),
      },
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: channels[1].id,
        saleDate: new Date('2024-09-03'),
        unitsSold: 11,
        avgUnitPrice: D('12.00'),
        promoFlag: false,
        returnRate: D('1.80'),
        grossMargin: D('110.00'),
      },
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: channels[0].id,
        saleDate: new Date('2024-09-04'),
        unitsSold: 10,
        avgUnitPrice: D('12.50'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('100.00'),
      },
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: null,
        saleDate: new Date('2024-09-05'),
        unitsSold: 12,
        avgUnitPrice: D('11.00'),
        promoFlag: true,
        returnRate: D('1.50'),
        grossMargin: D('108.00'),
      },

      // Period 2: Medium price ($10.80), medium demand (14-18 units)
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-01'),
        unitsSold: 15,
        avgUnitPrice: D('11.00'),
        promoFlag: false,
        returnRate: D('1.40'),
        grossMargin: D('135.00'),
      },
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-02'),
        unitsSold: 14,
        avgUnitPrice: D('10.50'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('119.00'),
      },
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: null,
        saleDate: new Date('2024-10-03'),
        unitsSold: 16,
        avgUnitPrice: D('10.80'),
        promoFlag: false,
        returnRate: D('1.70'),
        grossMargin: D('144.00'),
      },
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-04'),
        unitsSold: 17,
        avgUnitPrice: D('11.20'),
        promoFlag: true,
        returnRate: null,
        grossMargin: D('153.00'),
      },
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-05'),
        unitsSold: 18,
        avgUnitPrice: D('10.00'),
        promoFlag: false,
        returnRate: D('1.30'),
        grossMargin: D('144.00'),
      },

      // Period 3: Lower price ($9.60), higher demand (20-24 units)
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-18'),
        unitsSold: 22,
        avgUnitPrice: D('9.80'),
        promoFlag: false,
        returnRate: D('1.10'),
        grossMargin: D('172.80'),
      },
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: null,
        saleDate: new Date('2024-10-19'),
        unitsSold: 20,
        avgUnitPrice: D('9.40'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('148.00'),
      },
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-20'),
        unitsSold: 24,
        avgUnitPrice: D('9.60'),
        promoFlag: false,
        returnRate: D('1.60'),
        grossMargin: D('192.00'),
      },
      {
        productId: productBySku['BEAN-HAT-004'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-21'),
        unitsSold: 21,
        avgUnitPrice: D('10.00'),
        promoFlag: true,
        returnRate: null,
        grossMargin: D('168.00'),
      },

      // Product 5 (TECH-HOOD-005) - Economic progression: $65 -> $58.50 -> $52
      // Period 1: Higher price ($65), lower demand (5-8 units)
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: channels[0].id,
        saleDate: new Date('2024-09-01'),
        unitsSold: 6,
        avgUnitPrice: D('66.00'),
        promoFlag: false,
        returnRate: D('2.40'),
        grossMargin: D('198.00'),
      },
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: null,
        saleDate: new Date('2024-09-02'),
        unitsSold: 5,
        avgUnitPrice: D('64.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('160.00'),
      },
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: channels[1].id,
        saleDate: new Date('2024-09-03'),
        unitsSold: 7,
        avgUnitPrice: D('65.00'),
        promoFlag: false,
        returnRate: D('1.90'),
        grossMargin: D('227.50'),
      },
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: channels[0].id,
        saleDate: new Date('2024-09-04'),
        unitsSold: 6,
        avgUnitPrice: D('67.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('201.00'),
      },
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: null,
        saleDate: new Date('2024-09-05'),
        unitsSold: 8,
        avgUnitPrice: D('63.00'),
        promoFlag: true,
        returnRate: D('2.10'),
        grossMargin: D('248.00'),
      },

      // Period 2: Medium price ($58.50), medium demand (9-13 units)
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-01'),
        unitsSold: 10,
        avgUnitPrice: D('59.00'),
        promoFlag: false,
        returnRate: D('1.80'),
        grossMargin: D('295.00'),
      },
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-02'),
        unitsSold: 9,
        avgUnitPrice: D('58.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('261.00'),
      },
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: null,
        saleDate: new Date('2024-10-03'),
        unitsSold: 11,
        avgUnitPrice: D('58.50'),
        promoFlag: false,
        returnRate: D('2.20'),
        grossMargin: D('321.75'),
      },
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-04'),
        unitsSold: 12,
        avgUnitPrice: D('59.50'),
        promoFlag: true,
        returnRate: null,
        grossMargin: D('357.00'),
      },
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-05'),
        unitsSold: 13,
        avgUnitPrice: D('57.00'),
        promoFlag: false,
        returnRate: D('1.60'),
        grossMargin: D('364.00'),
      },

      // Period 3: Lower price ($52), higher demand (15-19 units)
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-18'),
        unitsSold: 17,
        avgUnitPrice: D('52.50'),
        promoFlag: false,
        returnRate: D('1.40'),
        grossMargin: D('446.25'),
      },
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: null,
        saleDate: new Date('2024-10-19'),
        unitsSold: 15,
        avgUnitPrice: D('51.00'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('382.50'),
      },
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-20'),
        unitsSold: 19,
        avgUnitPrice: D('52.00'),
        promoFlag: false,
        returnRate: D('1.90'),
        grossMargin: D('494.00'),
      },
      {
        productId: productBySku['TECH-HOOD-005'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-21'),
        unitsSold: 16,
        avgUnitPrice: D('53.00'),
        promoFlag: true,
        returnRate: null,
        grossMargin: D('424.00'),
      },

      // Product 6 (SPORT-CAP-006) - Economic progression: $15 -> $13.50 -> $12
      // Period 1: Higher price ($15), lower demand (10-14 units)
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: channels[0].id,
        saleDate: new Date('2024-09-01'),
        unitsSold: 12,
        avgUnitPrice: D('15.50'),
        promoFlag: false,
        returnRate: D('1.30'),
        grossMargin: D('144.00'),
      },
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: null,
        saleDate: new Date('2024-09-02'),
        unitsSold: 10,
        avgUnitPrice: D('14.50'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('115.00'),
      },
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: channels[1].id,
        saleDate: new Date('2024-09-03'),
        unitsSold: 13,
        avgUnitPrice: D('15.00'),
        promoFlag: false,
        returnRate: D('1.80'),
        grossMargin: D('156.00'),
      },
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: channels[0].id,
        saleDate: new Date('2024-09-04'),
        unitsSold: 11,
        avgUnitPrice: D('15.50'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('132.00'),
      },
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: null,
        saleDate: new Date('2024-09-05'),
        unitsSold: 14,
        avgUnitPrice: D('14.00'),
        promoFlag: true,
        returnRate: D('1.50'),
        grossMargin: D('154.00'),
      },

      // Period 2: Medium price ($13.50), medium demand (16-20 units)
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-01'),
        unitsSold: 17,
        avgUnitPrice: D('13.75'),
        promoFlag: false,
        returnRate: D('1.40'),
        grossMargin: D('195.25'),
      },
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-02'),
        unitsSold: 16,
        avgUnitPrice: D('13.25'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('176.00'),
      },
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: null,
        saleDate: new Date('2024-10-03'),
        unitsSold: 18,
        avgUnitPrice: D('13.50'),
        promoFlag: false,
        returnRate: D('1.70'),
        grossMargin: D('202.50'),
      },
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-04'),
        unitsSold: 19,
        avgUnitPrice: D('13.80'),
        promoFlag: true,
        returnRate: null,
        grossMargin: D('218.50'),
      },
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-05'),
        unitsSold: 20,
        avgUnitPrice: D('13.00'),
        promoFlag: false,
        returnRate: D('1.20'),
        grossMargin: D('210.00'),
      },

      // Period 3: Lower price ($12), higher demand (22-26 units)
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-18'),
        unitsSold: 24,
        avgUnitPrice: D('12.25'),
        promoFlag: false,
        returnRate: D('1.10'),
        grossMargin: D('234.00'),
      },
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: null,
        saleDate: new Date('2024-10-19'),
        unitsSold: 22,
        avgUnitPrice: D('11.75'),
        promoFlag: false,
        returnRate: null,
        grossMargin: D('205.50'),
      },
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: channels[1].id,
        saleDate: new Date('2024-10-20'),
        unitsSold: 26,
        avgUnitPrice: D('12.00'),
        promoFlag: false,
        returnRate: D('1.60'),
        grossMargin: D('260.00'),
      },
      {
        productId: productBySku['SPORT-CAP-006'],
        channelId: channels[0].id,
        saleDate: new Date('2024-10-21'),
        unitsSold: 23,
        avgUnitPrice: D('12.50'),
        promoFlag: true,
        returnRate: null,
        grossMargin: D('230.00'),
      },
    ],
    skipDuplicates: true,
  });

  console.log('    ✅ Sales data seeded with economic progression patterns');
}
