import type { Product, SimulationEvent } from '@/app/agent-run/types';

export const MAX_DAYS = 7;

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'beanie',
    name: 'Beanie Hat',
    sku: 'BEAN-HAT-004',
    category: 'Accessories',
    urgency: 'URGENT',
    urgencyColor: 'red',
    initialStock: 400,
    currentStock: 400,
    soldUnits: 0,
    basePrice: 12.0,
    currentPrice: 12.0,
    currentDiscount: 0,
    daysLeft: 4,
    holdingCostPerDay: 20,
    targetSellThrough: 90,
    currentSellThrough: 0,
    salesVelocity: 12.1,
    status: 'monitoring',
    activeChannels: [],
    totalRevenue: 0,
    agentFocus: false,
  },
  {
    id: 'summer',
    name: 'Summer Top',
    sku: 'SUM-TOP-002',
    category: 'Apparel',
    urgency: 'MODERATE',
    urgencyColor: 'yellow',
    initialStock: 260,
    currentStock: 260,
    soldUnits: 0,
    basePrice: 35.0,
    currentPrice: 35.0,
    currentDiscount: 0,
    daysLeft: 14,
    holdingCostPerDay: 26,
    targetSellThrough: 75,
    currentSellThrough: 0,
    salesVelocity: 9.7,
    status: 'monitoring',
    activeChannels: [],
    totalRevenue: 0,
    agentFocus: false,
  },
  {
    id: 'shoes',
    name: 'Running Shoes',
    sku: 'RUN-SHOE-003',
    category: 'Footwear',
    urgency: 'ON TRACK',
    urgencyColor: 'green',
    initialStock: 80,
    currentStock: 80,
    soldUnits: 0,
    basePrice: 100.0,
    currentPrice: 100.0,
    currentDiscount: 0,
    daysLeft: 45,
    holdingCostPerDay: 15,
    targetSellThrough: 60,
    currentSellThrough: 0,
    salesVelocity: 4.8,
    status: 'monitoring',
    activeChannels: [],
    totalRevenue: 0,
    agentFocus: false,
  },
  {
    id: 'jacket',
    name: 'Winter Jacket',
    sku: 'WIN-JKT-001',
    category: 'Apparel',
    urgency: 'ON TRACK',
    urgencyColor: 'green',
    initialStock: 120,
    currentStock: 120,
    soldUnits: 0,
    basePrice: 90.0,
    currentPrice: 90.0,
    currentDiscount: 0,
    daysLeft: 76,
    holdingCostPerDay: 30,
    targetSellThrough: 50,
    currentSellThrough: 0,
    salesVelocity: 7.2,
    status: 'monitoring',
    activeChannels: [],
    totalRevenue: 0,
    agentFocus: false,
  },
];

export const SIMULATION_PLAN: Readonly<Record<number, SimulationEvent[]>> = {
  0: [
    {
      productId: 'all',
      action: 'INITIAL_SCAN',
      message: '🤖 Agent starting inventory analysis...',
      type: 'system',
    },
    {
      productId: 'beanie',
      action: 'IDENTIFY_URGENT',
      message: '⚠️ URGENT: Beanie Hat - Only 4 days left, 400 units at risk',
      type: 'alert',
    },
    {
      productId: 'summer',
      action: 'IDENTIFY_MODERATE',
      message: '📊 MODERATE: Summer Top - 14 days left, declining season',
      type: 'warning',
    },
  ],
  1: [
    {
      productId: 'beanie',
      action: 'APPLY_MARKDOWN',
      message: '💰 Applying 35% markdown to Beanie Hat → $7.80',
      discount: 35,
      channels: ['email', 'instagram'],
      type: 'action',
    },
    {
      productId: 'summer',
      action: 'APPLY_MARKDOWN',
      message: '💰 Applying 25% markdown to Summer Top → $26.25',
      discount: 25,
      channels: ['email'],
      type: 'action',
    },
    {
      productId: 'all',
      action: 'CHANNELS_ACTIVATED',
      message: '📢 Marketing channels activated for 2 products',
      type: 'channel',
    },
  ],
  2: [
    {
      productId: 'beanie',
      action: 'MONITOR',
      message: '📈 Beanie Hat: 67 units sold (target was 100)',
      type: 'analysis',
    },
    {
      productId: 'summer',
      action: 'MONITOR',
      message: '✅ Summer Top: On track - 31 units sold',
      type: 'success',
    },
  ],
  3: [
    {
      productId: 'beanie',
      action: 'INCREASE_MARKDOWN',
      message:
        '🔴 URGENT ADJUSTMENT: Beanie Hat markdown increased to 45% → $6.60',
      discount: 45,
      channels: ['email', 'instagram', 'sms'],
      type: 'urgent',
    },
    {
      productId: 'shoes',
      action: 'APPLY_MARKDOWN',
      message: '💰 Initiating 20% markdown on Running Shoes → $80.00',
      discount: 20,
      channels: ['website'],
      type: 'action',
    },
  ],
  4: [
    {
      productId: 'beanie',
      action: 'SUCCESS',
      message: '🎯 Beanie Hat velocity increased 250%! 142 units sold today',
      type: 'success',
    },
    {
      productId: 'summer',
      action: 'INCREASE_MARKDOWN',
      message: '📊 Summer Top markdown increased to 40% → $21.00',
      discount: 40,
      channels: ['email', 'instagram', 'sms'],
      type: 'action',
    },
  ],
  5: [
    {
      productId: 'all',
      action: 'FINAL_PUSH',
      message: '🚀 Final push activated - All channels engaged',
      type: 'channel',
    },
    {
      productId: 'jacket',
      action: 'APPLY_MARKDOWN',
      message: '💰 Winter Jacket: Preventive 15% markdown → $76.50',
      discount: 15,
      channels: ['email'],
      type: 'action',
    },
  ],
  6: [
    {
      productId: 'beanie',
      action: 'NEAR_COMPLETE',
      message: '✅ Beanie Hat: 89% cleared! Only 44 units remaining',
      type: 'success',
    },
    {
      productId: 'summer',
      action: 'PROGRESS',
      message: '📊 Summer Top: 68% cleared, exceeding targets',
      type: 'success',
    },
  ],
  7: [
    {
      productId: 'all',
      action: 'COMPLETION',
      message:
        '🎉 Campaign Complete: $2,156 profit recovered, $1,200 holding costs saved',
      type: 'success',
    },
    {
      productId: 'beanie',
      action: 'FINAL',
      message: '✅ Beanie Hat: 91% clearance achieved',
      type: 'success',
    },
    {
      productId: 'summer',
      action: 'FINAL',
      message: '✅ Summer Top: 72% clearance achieved',
      type: 'success',
    },
  ],
};
